# jetbot_qr_code topics
cmd_raw_topic: cmd_raw
cmd_str_topic: cmd_str
cmd_vel_topic: cmd_vel
turning_topic: turning
markers_topic: markers

markers_image_topic: markers_image
turning_image_topic: turning_image

# other node topics
raw_camera_topic: /jetbot_ros/jetbot_camera/raw

# robot params
wheelbase_meters: 0.10
wheel_radius_meters: 0.03
max_speed: 0.015

# image processing params
camera_matrix:   [[ 788.24693847,    0.        ,  602.05667635],
                  [   0.        ,  782.9304954 ,  400.38415523],
                  [   0.        ,    0.        ,    1.        ]]
camera_dist:    [[-0.34775177,  0.1647844 , -0.00131214,  0.00067494, -0.04547439]]
aruco_side_length: 0.0935

# hsv filtering limits
lower_color: [20, 100, 100]
upper_color: [50, 255, 255]
