# jetbot_qr_code topics
cmd_raw_topic: cmd_raw
cmd_str_topic: cmd_str
cmd_vel_topic: cmd_vel
turning_topic: turning
markers_topic: markers

markers_image_topic: markers_image
turning_image_topic: turning_image
final_image_topic: final_image

# other node topics
raw_camera_topic: /webcam/image_raw

# robot params
wheelbase_meters: 0.10
wheel_radius_meters: 0.03
max_speed: 0.015
left_adj: 1.0
right_adj: 0.75

# image processing params
camera_matrix:   [[ 788.24693847,    0.        ,  602.05667635],
                  [   0.        ,  782.9304954 ,  400.38415523],
                  [   0.        ,    0.        ,    1.        ]]
camera_dist:    [[-0.34775177,  0.1647844 , -0.00131214,  0.00067494, -0.04547439]]
aruco_side_length: 0.0935

# hsv filtering limits
# with max values of [359, 100, 100]
lower_color: [180, 100, 100]
upper_color: [240, 100, 100]
