cmd_raw_topic: cmd_raw
cmd_str_topic: cmd_str
cmd_vel_topic: cmd_vel

wheelbase_meters: 0.10
wheel_radius_meters: 0.03

raw_camera_topic: /jetbot_ros/jetbot_camera/raw

camera_matrix:   [[ 788.24693847,    0.        ,  602.05667635],
                  [   0.        ,  782.9304954 ,  400.38415523],
                  [   0.        ,    0.        ,    1.        ]]
camera_dist:    [[-0.34775177,  0.1647844 , -0.00131214,  0.00067494, -0.04547439]]
